# Generated by Django 4.1.3 on 2022-11-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_Details',
            fields=[
                ('User_Name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Staff_ID', models.IntegerField(unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Mail_ID', models.EmailField(max_length=254)),
                ('Photo', models.ImageField(upload_to='Staff_Images/')),
            ],
            options={
                'db_table': 'Staff_Details',
            },
        ),
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('User_Name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Regno', models.IntegerField(unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=100)),
                ('Mail_ID', models.EmailField(max_length=254)),
                ('Photo', models.ImageField(upload_to='Student_Images/')),
                ('Biometric', models.ImageField(upload_to='Student_Biometric/')),
            ],
            options={
                'db_table': 'Student_Details',
            },
        ),
    ]
